import { promises as fs } from 'fs';
import path from 'path';

async function walk(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  const files = await Promise.all(entries.map(async (entry) => {
    const res = path.resolve(dir, entry.name);
    return entry.isDirectory() ? walk(res) : res;
  }));
  return files.flat();
}

const __dirname = path.dirname(new URL(import.meta.url).pathname);

async function run() {
  const distDir = path.resolve(__dirname, 'dist');
  try {
    await fs.access(distDir);
  } catch (e) {
    console.error('dist directory not found. Please run `npm run build` in src/frontend-service first.');
    process.exit(1);
  }

  const files = await walk(distDir);
  const allowed = files.filter(f => /\.(html|js|css|svg|png|jpg|jpeg|gif|webp|ico|txt|json|map)$/i.test(f));

  const entries = [];
  for (const f of allowed) {
    const rel = path.relative(distDir, f).replace(/\\/g, '/');
    const content = await fs.readFile(f, 'utf-8');
    // Use JSON string literal to avoid template escaping issues
    entries.push({ rel, json: JSON.stringify(content) });
  }

  const outPath = path.resolve(__dirname, 'static-bundle.ts');
  const ts = `// Auto-generated by build_embed_assets.mjs. Do not edit manually.\n` +
`export const STATIC_FILES: Record<string, string> = {\n` +
entries.map(e => `  ${JSON.stringify(e.rel)}: ${e.json},`).join('\n') +
`\n};\n`;

  await fs.writeFile(outPath, ts, 'utf-8');
  console.log(`Wrote ${outPath} with ${entries.length} files.`);
}

run().catch(err => { console.error(err); process.exit(1); });
